### send
POST http://localhost:8765/hefmq/send?topic=aa
Content-Type: application/json

{
  "id": 3,
  "body": "hello mq demo!"
}


### subscribe
POST http://localhost:8765/hefmq/subscribe?topic=com.hef.demo&consumerId=cs01
Content-Type: application/json

{
}

### unsubscribe
POST http://localhost:8765/hefmq/unsubscribe?topic=aa&consumerId=cs01
Content-Type: application/json

{
}

### receive
POST http://localhost:8765/hefmq/receive?topic=com.hef.demo&consumerId=cs01
Content-Type: application/json

{
}


### batchReceive
POST http://localhost:8765/hefmq/batchReceive?topic=com.hef.demo&consumerId=cs01&size=5
Content-Type: application/json

{
}

### ack
POST http://localhost:8765/hefmq/ack?topic=com.hef.demo&consumerId=cs01&offset=1073
Content-Type: application/json

{
}
